apiVersion: v1
kind: ServiceAccount
metadata:
  name: nyc-taxi-demand-sa
  namespace: default
  annotations:
    # TODO(you): set to the serving_irsa_role_arn output from terraform/ephemeral.
    eks.amazonaws.com/role-arn: "arn:aws:iam::<ACCOUNT_ID>:role/nyc-taxi-demand-serving-irsa"
